# Generated by Django 2.2 on 2019-07-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('city', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('confirmation', models.BooleanField(null=True)),
            ],
        ),
    ]
