# Generated by Django 2.2 on 2019-07-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='start_hour',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hour_end',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='hour_start',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
