# Generated by Django 2.2 on 2019-07-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190720_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='confirmation',
        ),
    ]
